[package]
name = "libsodium-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.63"
pkg-config = "0.3"

[dev-dependencies]
hex = "0.4"
